services:
  - type: web
    name: prompt2pic-ai
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_HOST
        value: prompt2pic-ai.onrender.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://prompt2pic-ai.onrender.com/
      - key: GENERIC_TIMEZONE
        value: Asia/Kolkata

      # Postgres (Supabase)
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        sync: false
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        sync: false
      - key: DB_POSTGRESDB_USER
        sync: false
      - key: DB_POSTGRESDB_PASSWORD
        sync: false
      - key: DB_POSTGRESDB_SCHEMA
        value: public